# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fetchmail_Bot
on:
  push:
    branches: "**"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - run: pip install nox==2022.1.7
      - run: pip install poetry==1.1.13
      # - run: nox
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E402,E501 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run bandit - lint
        run: |
          pip install bandit
          bandit -s B605 *
        # continue-on-error: true


      - name: black - static security code check
        run: |
          pip install black
          black --verbose common/.
          black --verbose fetchmail_bot.py

      - name: Test with pytest
        run: |
          pip install pytest
          # pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests

      - name: vulernability check in dependcies
        run: |
          pip install safety
          safety check --full-report
